name: anchor
description: "An app with calming ('anchoring') songs to listen to when stressed"
publish_to: 'none'

version: 1.2.6+14

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  heroicons: ^0.10.0
  shared_preferences: ^2.2.3
  just_audio: ^0.9.38
  provider: ^6.1.2
  collection: ^1.18.0
  google_fonts: ^6.2.1
  just_audio_background: ^0.0.1-beta.13
  audio_video_progress_bar: ^2.0.3
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/northern-lights.jpg
    - assets/images/sea.jpg
    - assets/images/stars.jpg
    - assets/images/sunset.jpg

    - assets/images/level-1-album-art.png
    - assets/images/level-2-album-art.png
    - assets/images/level-3-album-art.png

    - assets/tracks/breeze.ogg
    - assets/tracks/change.ogg
    - assets/tracks/difference.ogg
    - assets/tracks/drifting.ogg
    - assets/tracks/float.ogg
    - assets/tracks/halls.ogg
    - assets/tracks/homes.ogg
    - assets/tracks/motions.ogg
    - assets/tracks/openings.ogg
    - assets/tracks/signs.mp3
    - assets/tracks/sleepy.ogg
    - assets/tracks/summer.ogg
    - assets/tracks/trains.ogg
    - assets/tracks/walks.ogg
    - assets/tracks/warm.mp3

